using Gua.Core;

namespace Gua.Testing;

public sealed record GuaNodeSnapshot(
    string Id,
    string Role,
    string Label,
    GuaBounds Bounds,
    bool Visible,
    bool Enabled,
    IReadOnlyList<string> Actions,
    string? ParentId = null,
    string? Text = null,
    string? Value = null,
    bool? Focused = null,
    bool? Hovered = null,
    bool? Pressed = null,
    bool? Checked = null,
    bool? Selected = null,
    int? SchemaVersion = null,
    ulong? SessionEpoch = null,
    ulong? FrameSequence = null,
    ulong? Revision = null,
    long? CaretPosition = null,
    long? SelectionStart = null,
    long? SelectionEnd = null,
    double? ScrollX = null,
    double? ScrollY = null,
    double? ScrollMaxX = null,
    double? ScrollMaxY = null,
    double? RangeValue = null,
    double? RangeMin = null,
    double? RangeMax = null,
    long? SelectedIndex = null);
